name: Build and Run Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Install Gradle
      uses: gradle/gradle-build-action@v2

    - name: Initialize Gradle Wrapper
      run: gradle wrapper

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Java Application
      run: java -jar "build/libs/Advent Of Code Solutions-1.0.jar"
