name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Initialize Gradle Wrapper
      uses: gradle/gradle-build-action@v2
      with:
        arguments: wrapper

    - name: Build with Gradle
      run: ./gradlew build
